set -o errexit

TESTS=(
TATCCGTCCG GAAAAATCCG
GCCTGCCTAT GCCTAAAAAG
TGCCTTA TAGCAGCCC
CCC CACCCACA
TTGGGAA CCGAATA
GACAT ACACTCCCAT
GAG AGGATAAGT
CACGCTCGT ACACT
GTTTA TCTTTCTGC
TCAACAAAGG CAA
CTTATAAT CCTACCG
GG GGTCA
"" AAT
CGATGT TGTGA
AGTGG TGGGGTAGT
CGAG CGAG
GGCGAA GGACCA
CTCCTCGGA ACCTCGTCTG
TTTCCAG TTGTTCA
CGGGGGC CCGGCCG
CTATATAAAC CTCGTAA
TTAATTAGTT GACGTTAATT
TAAG TAAGACCGC
GGCGA GGTTTTA
GGCTGC GCTCCAA
CTGGGGAG CCACCTGGGC
CATTTCACGA TCGCCC
GCC CGACGAGCCC
AGAGAAAAA AAAA
)

for ((i=0; i<${#TESTS[@]}; i+=2)); do
    python test.py "${TESTS[i]}" "${TESTS[i+1]}"
done
