set -o errexit

TESTS=(
TATCCGTCCG GAAAAATCCG
GCCTGCCTAT GCCTAAAAAG
TGCCTTA TAGCAGCCC
CCC CACCCACA
TTGGGAA CCGAATA
GACAT ACACTCCCAT
GAG AGGATAAGT
CACGCTCGT ACACT
GTTTA TCTTTCTGC
TCAACAAAGG CAA
CTTATAAT CCTACCG
GG GGTCA
"" AAT
CGATGT TGTGA
AGTGG TGGGGTAGT
CGAG CGAG
GGCGAA GGACCA
CTCCTCGGA ACCTCGTCTG
TTTCCAG TTGTTCA
CGGGGGC CCGGCCG
CTATATAAAC CTCGTAA
TTAATTAGTT GACGTTAATT
TAAG TAAGACCGC
GGCGA GGTTTTA
GGCTGC GCTCCAA
CTGGGGAG CCACCTGGGC
CATTTCACGA TCGCCC
GCC CGACGAGCCC
AGAGAAAAA AAAA
#from algebra
"" ""
"" C
C ""
C G
CATC GATG
AGAATTGCTTGAA AGGGTTAAA
CTCTAGAGACTTTATTTTCCAC GTCTCAGACTTTCTTTATCCCC
ATATACCTTTTA CTATAGCCTTTTTC
CAGGGGAAGTG GCAGGGGCCTA
TCGTGGT CTAACAT
TGCATTAGGGCAAGGGTCTTCGACTTTCCACGAAAATCGCGTCGGTTTGAC TGCATTAGGGCAAGGGTCTTCGACTTCCACGAAAATCGCGTCGGTTTGAC
TGCATTAGGGCAAGGGTCTTCGACTTTCCACGAAAATCGCGTCGGTTTGAC TGCATTAGGGCAAGGGTCTTCGACTTCCACGAAAATCGCGTCGGTTGAC
CTCGGCATTA GGCTGGCTGT
TTT TTTTAT
TTTTAT TTT
TTAATTGACA CTACTGAGTT
TCTCTATCGTA TCTA
AAAATA GAAAAGAAA
CATATATCG CTTATAGCAT
TCTC TC
TTGTA TTTGTGTT
AA ACA
ACA AA
# paper
ACCTGACT ATCTTACTT
)

for ((i=0; i<${#TESTS[@]}; i+=2)); do
    python test.py "${TESTS[i]}" "${TESTS[i+1]}"
done
