from algebra.relations import Relation, compare
import pytest


@pytest.mark.parametrize("reference, lhs, rhs, expected", [
    ("A", "B", "B", Relation.EQUIVALENT),
    ("AAA", "AAB", "AAB", Relation.EQUIVALENT),
    ("AAA", "AA", "AA", Relation.EQUIVALENT),
    ("AAA", "CAAA", "CAAA", Relation.EQUIVALENT),
    ("AAA", "", "", Relation.EQUIVALENT),
    ("AAA", "ABB", "ABB", Relation.EQUIVALENT),
    ("AA", "AB", "BB", Relation.IS_CONTAINED),
    ("AAA", "AAB", "ABB", Relation.IS_CONTAINED),
    ("", "A", "AA", Relation.IS_CONTAINED),
    ("", "AB", "ABAB", Relation.IS_CONTAINED),
    ("ATATA", "ATATAB", "ATBTAB", Relation.IS_CONTAINED),
    ("", "BB", "BAB", Relation.IS_CONTAINED),
    ("CATATATC", "CATATTATC", "CATATATATC", Relation.IS_CONTAINED),
    ("AA", "BB", "AB", Relation.CONTAINS),
    ("AAA", "ABB", "AAB", Relation.CONTAINS),
    ("", "AA", "A", Relation.CONTAINS),
    ("", "ABAB", "AB", Relation.CONTAINS),
    ("ATATA", "ATBTAB", "ATATAB", Relation.CONTAINS),
    ("", "BAB", "BB", Relation.CONTAINS),
    ("CATATATC", "CATATATATC", "CATATTATC", Relation.CONTAINS),
    ("A", "B", "C", Relation.OVERLAP),
    ("AAA", "ABC", "ABD", Relation.OVERLAP),
    ("AAA", "BBA", "ABB", Relation.OVERLAP),
    ("", "BC", "CAB", Relation.OVERLAP),
    ("ATA", "BTA", "ATB", Relation.DISJOINT),
    ("AAA", "BAA", "AAA", Relation.DISJOINT),
    ("AAA", "AAA", "AAB", Relation.DISJOINT),
    ("AAA", "BAAA", "AAAB", Relation.DISJOINT),
    ("AAA", "AAAB", "BAAA", Relation.DISJOINT),
    ("", "A", "B", Relation.DISJOINT),
    ("T", "GG", "GGTA", Relation.OVERLAP),
    ("TC", "GTC", "GAA", Relation.IS_CONTAINED),
    ("T", "GC", "CT", Relation.CONTAINS),
    ("CT", "TG", "GC", Relation.DISJOINT),
    ("A", "ABD", "ABC", Relation.OVERLAP),
    ("A", "AB", "AC", Relation.DISJOINT),
    ("AAA", "BAAA", "AAAB", Relation.DISJOINT),
    ("A", "BAC", "BAD", Relation.OVERLAP),
    ("AA", "BAAC", "BAAD", Relation.OVERLAP),
    ("AAA", "BAAAC", "BAAAD", Relation.OVERLAP),
    ("TGTA", "CTGCT", "TAGGAACG", Relation.DISJOINT),
    ("CT", "GT", "AT", Relation.OVERLAP),
])
def test_compare(reference, lhs, rhs, expected):
    relation = compare(reference, lhs, rhs)
    assert relation == expected
